# Installation des dépendances pour CI
install:
	pip install --upgrade pip &&\
		pip install -r requirements.txt

# (Optionnel) formatage du code - pour l'instant on ne fait rien
format:
	echo "No formatting step yet"

# Entraînement du modèle Iris
train:
	python train.py

# Génération du rapport CML (commentaire automatique sous le commit)
eval:
	echo "## Model Metrics" > report.md
	cat ./Results/metrics.txt >> report.md

	echo '\n## Confusion Matrix' >> report.md
	echo '![Confusion Matrix](./Results/model_results.png)' >> report.md

	cml comment create report.md
